- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: nginxppastable

- name: Install Nginx
  apt: pkg=nginx state=latest update_cache=true
  when: nginxppastable|success
  register: nginxinstalled
  notify:
    - Start Nginx