---
- name: Add php.ini Config
  when: phpfpminstalled|success
  template: src=php.ini.j2 dest=/etc/php5/fpm/conf.d/00-php.ini owner=root group=root

- name: Add pool Config
  when: phpfpminstalled|success
  template: src=pool.conf.j2 dest=/etc/php5/fpm/pool.d/www.conf owner=root group=root
